# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Get Paper and build NMS
      run: wget -o paper.jar https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/709/downloads/paper-1.16.5-709.jar && java -Dpaperclip.install=true -jar paper.jar
    - name: Build with Maven
      run: mvn -B package --file pom.xml
